# @format

name: Paris sportifs
on:
    push:
        branches: ["main"]

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3 # utilise l’action checkout@v3 pour copier le code sur la machine virtuelle qui exécute les tâches
            - name: Test python Code # nom de l’étape suivante
              # Exécute les tests unitaires sur le code source à l’aide de l’outil de test pytest. Au préalable, les dependances nécessaires ont été installées et nous nous sommes positionné dans l'emplacement d'exécution des test
              run: |
                  pip3 install -r requirements.txt 
                  cd codes/api/
                  pytest

    build:
        needs: test
        runs-on: ubuntu-latest
        steps:
            - name: executing remote ssh commands
              uses: appleboy/ssh-action@master
              with:
                  host: ${{ secrets.HOSTNAME  }}
                  username: ubuntu
                  key: ${{ secrets.AWS_PRIVATE_KEY  }}
                  port: 22

                  script: |
                      cd /home/ubuntu/test_ssh_paris_sportifs
                      git pull
