# @format

name: Paris sportifs
on:
    push:
        branches: [master]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: executing remote ssh commands
              uses: appleboy/ssh-action@master
              with:
                  host: ${{ secrets.HOSTNAME  }}
                  username: ubuntu
                  key: ${{ secrets.AWS_PRIVATE_KEY  }}
                  port: 22

                  script: |
                      git pull
